# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import usuario_pb2 as usuario__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in usuario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarUsuario = channel.unary_unary(
                '/UsuarioService/CriarUsuario',
                request_serializer=usuario__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=usuario__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/UsuarioService/Login',
                request_serializer=usuario__pb2.LoginRequest.SerializeToString,
                response_deserializer=usuario__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.VerificarUsuario = channel.unary_unary(
                '/UsuarioService/VerificarUsuario',
                request_serializer=usuario__pb2.VerificarUsuarioRequest.SerializeToString,
                response_deserializer=usuario__pb2.VerificarUsuarioResponse.FromString,
                _registered_method=True)


class UsuarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerificarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarUsuario,
                    request_deserializer=usuario__pb2.UsuarioRequest.FromString,
                    response_serializer=usuario__pb2.UsuarioResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=usuario__pb2.LoginRequest.FromString,
                    response_serializer=usuario__pb2.LoginResponse.SerializeToString,
            ),
            'VerificarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarUsuario,
                    request_deserializer=usuario__pb2.VerificarUsuarioRequest.FromString,
                    response_serializer=usuario__pb2.VerificarUsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UsuarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UsuarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UsuarioService/CriarUsuario',
            usuario__pb2.UsuarioRequest.SerializeToString,
            usuario__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UsuarioService/Login',
            usuario__pb2.LoginRequest.SerializeToString,
            usuario__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerificarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UsuarioService/VerificarUsuario',
            usuario__pb2.VerificarUsuarioRequest.SerializeToString,
            usuario__pb2.VerificarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
