# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuario.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'usuario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rusuario.proto\"a\n\x0fPacienteRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x10\n\x08problema\x18\x02 \x01(\t\x12\x10\n\x08telefone\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\r\n\x05senha\x18\x05 \x01(\t\"7\n\x10PacienteResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x11\n\tid_gerado\x18\x02 \x01(\x05\x32\x46\n\x0eUsuarioService\x12\x34\n\rCriarPaciente\x12\x10.PacienteRequest\x1a\x11.PacienteResponseB#\n\x11\x63om.hospital.grpcB\x0cUsuarioProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.hospital.grpcB\014UsuarioProtoP\001'
  _globals['_PACIENTEREQUEST']._serialized_start=17
  _globals['_PACIENTEREQUEST']._serialized_end=114
  _globals['_PACIENTERESPONSE']._serialized_start=116
  _globals['_PACIENTERESPONSE']._serialized_end=171
  _globals['_USUARIOSERVICE']._serialized_start=173
  _globals['_USUARIOSERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
